Added new TimeSeries solution containing only Ingestion function for time series submit
Energinet-DataHub/geh-timeseries pull request #354
Opened 2022-01-18 11:04 UTC by jonasdmoeller

…time series

## Description

Added a new solution containing only a HttpTrigger function for submitting time series.

## References

* #326

2022-01-18 11:18 UTC, ZavezX requested changes

2022-01-18 11:18 UTC, ZavezX commented on source/TimeSeries/MessageReceiver/TimeSeriesIngestion.cs
> +            var response = request.CreateResponse(HttpStatusCode.OK);
Should return `202 - Accepted`.

2022-01-18 13:11 UTC, jonasdmoeller commented on source/TimeSeries/MessageReceiver/TimeSeriesIngestion.cs
> +            var response = request.CreateResponse(HttpStatusCode.OK);
Fixed

2022-01-19 08:21 UTC, johevemi commented on source/TimeSeries/MessageReceiver.IntegrationTests/MessageReceiver.IntegrationTests.csproj
> +        <TargetFramework>net6.0</TargetFramework>
Should we use dotNET version 5 instead of 6 in MessageReceiver.IntegrationTests.csproj as we do in MessageReceiver.csproj

2022-01-19 09:36 UTC, johevemi commented on source/TimeSeries/MessageReceiver.IntegrationTests/MessageReceiver.IntegrationTests.csproj
> +        <TargetFramework>net6.0</TargetFramework>
According to [ADR007](https://github.com/Energinet-DataHub/green-energy-hub/blob/main/docs/architecture-decision-record/ADR-0007%20-%20.NET%20upgrade%20path.md) we should not use any new major version of .NET in the first 3 months of release and since .NET 6  was released on November 8, 2021 we should not use it yet

2022-01-19 11:07 UTC, johevemi approved these changes

2022-01-19 13:59 UTC, ZavezX approved these changes

2022-01-21 08:09 UTC, ZavezX approved these changes

2022-01-21 08:11 UTC, johevemi approved these changes

2022-01-21 14:11 UTC, johevemi approved these changes

2022-01-21 14:23 UTC, merged