timeseries streaming from eventhub into datalake
Energinet-DataHub/geh-timeseries pull request #394
Opened 2022-02-14 10:37 UTC by kristianschneider

TBD

2022-02-14 14:15 UTC, ZavezX commented on source/databricks/package/eventhub_ingestor.py
> +    # streamingDF.awaitTermination()
Remove?

2022-02-15 06:50 UTC, lasrinnil commented on build/databricks_streaming_cluster/main/main.tf
> +         "--events-data-blob-name=timeseries"
That sounds like a good idea, could you perhaps post a link or some other reference for how the naming should be?

2022-02-15 07:27 UTC, ZavezX commented on build/databricks_streaming_cluster/main/main.tf
> +         "--events-data-blob-name=timeseries"
I don't necessary mean that we should use bronze, silver or gold in the naming. I just think that the name timeseries is not informative enough to reflect which stage/state the data is in. But the medallion architecture is shown [here](https://databricks.com/notebooks/delta-lake-cdf.html#:~:text=The%20medallion%20architecture%20takes%20raw,many%20customers%20implement%20in%20Databricks.).

2022-02-15 07:38 UTC, lasrinnil commented on source/databricks/streaming-jobs/streaming.py
> +
Could this file have a more describing name? 

streaming.py -> timeseries_persistor.py

2022-02-16 11:35 UTC, ZavezX requested changes

2022-02-16 11:35 UTC, ZavezX commented on build/databricks_streaming_cluster/main/kv.tf
> +}
Shouldn't this be saved in the keyvault in timeseries and not in shared?

2022-02-16 12:26 UTC, ZavezX approved these changes

2022-02-16 12:44 UTC, merged