Publish all historical time series points
Energinet-DataHub/geh-timeseries pull request #454
Opened 2022-04-06 11:50 UTC by BjarkeMeier

## Description

## References

* #616

2022-04-06 12:54 UTC, ZavezX requested changes

2022-04-06 12:54 UTC, ZavezX commented on source/databricks/package/timeseries_publisher.py
> +         col(Colname.registration_date_time)
Didn't we talk about using the `created_date_time` instead? Or perhaps the `encued_date_time` from the eventhub message?

2022-04-07 06:47 UTC, BjarkeMeier commented on source/databricks/package/timeseries_publisher.py
> +         col(Colname.registration_date_time)
According to the talk yesterday and settlement with PO and SME today it'll be EventHub enqueued time. I'm working on it.

2022-04-07 08:44 UTC, BjarkeMeier commented on source/databricks/package/timeseries_publisher.py
> +         col(Colname.registration_date_time)
Fixed. @ZavezX and @johevemi would you mind reviewing again?

2022-04-07 09:44 UTC, ZavezX approved these changes
Just some flake8 errors, otherwise it looks fine.

2022-04-07 10:29 UTC, merged